import 'package:flutter/widgets.dart';
import 'package:petrimonium_flutter_core/petrimonium_flutter_core.dart';
import 'package:petrimonium_shared_features/petrimonium_shared_features.dart';

import '../constants/app_strings.dart';

/// App-wide translator. pt-BR is the product's default language; en/es are
/// offered through the Settings screen.
///
/// The lookup itself lives in [TranslatorEngine]; this class is the product's
/// half of it. Copy every Petrimonium product words the same way comes from
/// `sharedCopy`; what stays here is only what this product says differently -
/// its brand voice, and the screens the other products do not have. Adding a
/// string that the sibling app already words identically belongs in
/// `sharedCopy`, not here.
///
/// The static surface is unchanged on purpose: 601 call sites already say
/// `Translator.translate(AppStrings.x)`, and none of them had to move.
class Translator {
  Translator._();

  static const String defaultLanguage = 'pt';
  static const Set<String> supportedLanguages = {'pt', 'pt_PT', 'en', 'es'};

  static final TranslatorEngine _engine = TranslatorEngine(
    base: sharedCopy,
    overrides: _productCopy,
    defaultLanguage: defaultLanguage,
    supportedLanguages: supportedLanguages,
  );

  static ValueNotifier<String> get languageNotifier => _engine.languageNotifier;

  static String get currentLanguage => _engine.currentLanguage;

  /// The current choice as a [Locale], for `MaterialApp.locale` — Flutter's
  /// own widgets (date picker, Cupertino dialogs) read this, not our codes.
  static Locale get currentLocale => _engine.currentLocale;

  /// Every offered language as a Locale, for `MaterialApp.supportedLocales`.
  static List<Locale> get supportedLocales => _engine.supportedLocales;

  /// Synchronous setter kept for tests and simple in-memory switches.
  /// Prefer [setLanguage] in the app so the preference is persisted.
  static set currentLanguage(String language) => _engine.currentLanguage = language;

  /// Loads the persisted language preference. Call once during app startup,
  /// before the first screen is built.
  static Future<void> load() => _engine.load();

  /// Updates the current language and persists it locally.
  /// Does not call the backend — callers that need the preference synced
  /// server-side (e.g. the Settings screen) should do that separately.
  static Future<void> setLanguage(String language) => _engine.setLanguage(language);

  /// [params] fills `{token}` placeholders in the translated string (e.g.
  /// `{petName}`) — used for copy that embeds the user's chosen pet name,
  /// which can't be baked into the static translation map.
  static String translate(String key, {Map<String, String>? params}) {
    if (key == AppStrings.homeStreakDaysLabel && params?['days'] == '1') {
      key = AppStrings.homeStreakDaySingular;
    } else if (key == AppStrings.companionAcademyReviewDue && params?['count'] == '1') {
      key = AppStrings.reviewDueSingular;
    }
    return _engine.translate(key, params: params);
  }

  /// Test-only escape hatch onto the *merged* catalogue (shared + product), so
  /// `translator_test.dart` keeps asserting parity over exactly what the app
  /// resolves at runtime, not over this file alone.
  static Map<String, Map<String, String>> get debugLocalizedValues => _engine.debugLocalizedValues;

  /// Test-only view of just this product's half, so a test can assert the
  /// halves stay disjoint — see `translator_test.dart`.
  static Map<String, Map<String, String>> get debugProductCopy => _productCopy;

  /// This product's own wording. Everything else comes from `sharedCopy`.
  static const Map<String, Map<String, String>> _productCopy = {
    'pt': {
      AppStrings.profileProgressUnavailable:
          'Não foi possível carregar seu progresso. Abra o Perfil novamente para tentar.',
      AppStrings.settingsSubtitle: 'Personalize sua experiência de aprendizado.',
      AppStrings.profileCommanderTitle: 'Seu aprendizado',
      AppStrings.appBarPlayerGenericGreeting: 'Nível {level} · {tier}',
      AppStrings.companionAcademyContinueLesson: 'Sua próxima aula é "{lessonTitle}". Vamos aprender?',
      AppStrings.companionAcademyReviewDue: 'Você tem {count} aulas para revisar. Vamos reforçar o que já aprendeu?',
      AppStrings.quizRetryInstruction: 'Toque na resposta correta, marcada em verde, para continuar.',
      AppStrings.homeStreakDaySingular: '{days} dia',
      AppStrings.reviewDueSingular: 'Você tem 1 aula para revisar. Vamos reforçar o que já aprendeu?',
      AppStrings.profileLearningProgress: '{count} aulas concluídas',
      AppStrings.profileLearningProgressOne: '1 aula concluída',
      AppStrings.profileLearningEmpty: 'Sua jornada começa com a primeira aula.',
      AppStrings.profileXp: '{xp} XP conquistados',

      AppStrings.simulatedHoldingQuantityPrice: '{quantity} un · PM {price}',
      AppStrings.simulatedHoldingAllocation: '{percent} carteira',

      AppStrings.academyRefreshError: 'Não foi possível atualizar seus dados. Puxe para atualizar.',
      AppStrings.missionDailyLessonTitle: 'Aula do Dia',
      AppStrings.missionDailyLessonDescription: 'Complete 1 aula hoje.',
      AppStrings.missionDailyTwoTitle: 'Dia Produtivo',
      AppStrings.missionDailyTwoDescription: 'Complete 2 aulas hoje.',
      AppStrings.missionWeeklyThreeTitle: 'Ritmo da Semana',
      AppStrings.missionWeeklyThreeDescription: 'Complete 3 aulas esta semana.',
      AppStrings.missionWeeklyModuleTitle: 'Módulo Completo',
      AppStrings.missionWeeklyModuleDescription: 'Complete um módulo inteiro esta semana.',
      AppStrings.investmentShortFixed: 'R. Fixa',
      AppStrings.investmentShortRealEstate: 'FIIs',

      AppStrings.brandTitle: 'Petrimonium',
      AppStrings.brandTagline: 'Aprenda a investir jogando',
      AppStrings.logoutConfirmTitle: 'Sair do Petrimonium Academy?',
      AppStrings.createAccount: 'Criar Conta',
      AppStrings.fillDetails: 'Preencha seus dados',
      AppStrings.alreadyHaveAccount: 'Já tem conta? Entrar',
      AppStrings.meetPetTitle: 'Dê um nome ao seu parceiro de jornada',
      AppStrings.meetPetIntro: 'Ele evolui com o que você aprende — nunca com quanto você tem.',
      AppStrings.financialGoalTitle: 'Qual é o seu objetivo agora?',
      AppStrings.financialGoalSubtitle: 'Isso ajusta sua trilha. Você pode mudar depois.',
      AppStrings.welcomeHeadline: 'Aprenda finanças praticando com segurança.',
      AppStrings.welcomeSubheadline: 'PETRIMONIUM ACADEMY',
      AppStrings.shareProgressCta: 'Baixe o Petrimonium Academy e comece sua jornada',
      AppStrings.inAppBrandName: 'Petrimonium Academy',
      AppStrings.academyIntroTitle: 'Sua trilha começa aqui',
      AppStrings.academyIntroSubtitle: 'Uma ordem sugerida — você escolhe por onde começar.',
      AppStrings.academyIntroStartsNow: 'começa agora',
      AppStrings.academyIntroMentorIntro: 'Vamos começar por {module}. {count} — dá pra começar agora.',
      AppStrings.academyIntroLessonSingular: 'aula',
      AppStrings.academyIntroLessonPlural: 'aulas',
      AppStrings.academyIntroMoreSchools: 'Mais {count} {unit} na trilha.',
      AppStrings.academyIntroSchoolSingular: 'escola',
      AppStrings.academyIntroSchoolPlural: 'escolas',
      AppStrings.gamificationIntroTitle: 'Como você progride aqui',
      AppStrings.gamificationIntroXpRuleTitle: 'XP por aprender',
      AppStrings.gamificationIntroXpRuleBody:
          'Você ganha XP completando aulas e práticas — nunca por valorização, aporte ou operação.',
      AppStrings.gamificationIntroStreakRuleTitle: 'Ofensiva sem punição',
      AppStrings.gamificationIntroStreakRuleBody:
          'Perder um dia não zera seu progresso nem te penaliza — o pet só fica com saudade.',
      AppStrings.gamificationIntroCompareRuleTitle: 'Sem comparação entre pessoas',
      AppStrings.gamificationIntroCompareRuleBody:
          'Seu progresso é só seu. Não existe ranking de patrimônio ou retorno aqui.',
      AppStrings.timeHorizonTitle: 'Para quando é esse objetivo?',
      AppStrings.timeHorizonSubtitle: 'Sem certeza? Tudo bem, é só um ponto de partida.',
      AppStrings.experienceLevelTitle: 'Como está sua experiência hoje?',
      AppStrings.experienceLevelSubtitle: 'Assim a Academy não te ensina o que você já sabe.',
      AppStrings.academyLessonCompleteTitle: 'Aula concluída!',
      AppStrings.academyLearningProgressPill: '+{xp} XP · progresso de aprendizado',
      AppStrings.academyContentLabel: 'CONTEÚDO EDUCATIVO',
      AppStrings.academyExampleLabel: 'EXEMPLO',
      AppStrings.academyLessonOfLabel: 'Aula {n} de {total}',
      AppStrings.mentorInterpretationLabel: 'MENTOR · INTERPRETAÇÃO DE IA',
      AppStrings.academyAllModulesTitle: 'Sua trilha completa',
      AppStrings.academyJourneySubtitle: 'Sua jornada de investimentos',
      AppStrings.academyJourneyExploreTooltip: 'Ver a trilha completa',
      AppStrings.academyJourneyYouAreHere: 'Você está aqui',
      AppStrings.academyJourneyUpNext: 'A seguir',
      AppStrings.academyJourneyContinueLesson: 'Continuar aula',
      AppStrings.academyJourneyStageProgress: '{completed} de {total} aulas',
      AppStrings.academyJourneyStageCompleted: '{completed}/{total} concluídas',
      AppStrings.academyJourneyStageTotalLessons: '{total} aulas',
      AppStrings.academyJourneyStageNotStarted: '{total} aulas · ainda não iniciada',
      AppStrings.academyJourneyModuleProgress: '{completed}/{total} aulas',
      AppStrings.academyJourneyBadgeInProgress: 'em andamento',
      AppStrings.academyJourneyLessonMinutes: '~{minutes} min',
      AppStrings.walletBridgeCtaLabel: 'Ver isso na sua carteira real',
      AppStrings.walletBridgeComingSoon: 'Em breve na Wallet',
      AppStrings.simulatedWalletTitle: 'Carteira Simulada',
      AppStrings.simulatedWalletDisclaimer:
          'Carteira de simulação: você informa os ativos e as datas, e as cotações são reais. Nenhuma ordem é executada e não há conexão com B3, corretora, banco ou exchange. Não é recomendação financeira — resultados simulados não garantem resultados reais.',
      AppStrings.simulatedWalletNoPositions:
          'Você ainda não tem posições simuladas. Que tal registrar sua primeira operação?',
      AppStrings.simulatedWalletResetAction: 'Reiniciar simulação',
      AppStrings.simulatedWalletResetConfirmTitle: 'Reiniciar simulação?',
      AppStrings.simulatedWalletResetConfirmMessage:
          'Isso apaga todas as posições e operações simuladas. Essa ação não pode ser desfeita.',
      AppStrings.simulatedWalletResetConfirmAction: 'Reiniciar',
      AppStrings.simulatedWalletResetSuccess: 'Simulação reiniciada',
      AppStrings.simulatedOrderScreenTitle: 'Nova operação simulada',
      AppStrings.simulatedOrderSearchHint: 'Buscar ativo (ex: PETR4)',
      AppStrings.simulatedOrderBuyLabel: 'Comprar',
      AppStrings.simulatedOrderSellLabel: 'Vender',
      AppStrings.simulatedOrderQuantityLabel: 'Quantidade',
      AppStrings.simulatedOrderReferencePriceLabel: 'Preço de referência (simulado)',
      AppStrings.simulatedOrderConfirmAction: 'Confirmar operação simulada',
      AppStrings.simulatedOrderSuccessMessage: 'Operação simulada registrada',
      AppStrings.simulatedOrderSelectAssetFirst: 'Busque e selecione um ativo primeiro',
      AppStrings.simulatedOrderDateLabel: 'Data da operação',
      AppStrings.simulatedOrderDateToday: 'Hoje',
      AppStrings.simulatedOrderHistoricalPriceLabel: 'Preço de fechamento em',
      AppStrings.simulatedOrderNoHistoricalQuote: 'Sem cotação disponível para esta data',
      AppStrings.simulatedWalletAllocationTitle: 'Alocação simulada',
      AppStrings.simulatedWalletTotalPatrimonyLabel: 'Patrimônio total simulado',
      AppStrings.simulatedWalletResultLabel: 'Resultado',
      AppStrings.simulatedWalletReturnLabel: 'Retorno sobre o investido',
      AppStrings.simulatedWalletPriceUnavailable: 'Preço indisponível',
      AppStrings.simulatedWalletHeaderSubtitle: 'Pratique investir, sem dinheiro de verdade',
      AppStrings.simulatedWalletAddAssetLabel: 'Adicionar',
      AppStrings.simulatedWalletMyAssetsLabel: 'MEUS ATIVOS SIMULADOS',
      AppStrings.simulatedWalletAllocationEmpty: 'Sem dados suficientes para calcular sua alocação.',
      AppStrings.simulatedWalletAllocationCenterLabel: 'TOTAL',
      AppStrings.simulatedWalletWealthBarsTitle: 'Evolução do patrimônio simulado',
      AppStrings.simulatedWalletWealthBarsRangeChip: '12 meses',
      AppStrings.simulatedWalletWealthBarsLegendInvested: 'Valor aplicado',
      AppStrings.simulatedWalletWealthBarsLegendGain: 'Ganho de capital',
      AppStrings.simulatedWalletWealthBarsLegendShortfall: 'Abaixo do aplicado',
      AppStrings.simulatedWalletWealthBarsEmpty: 'Ainda não há histórico suficiente para montar esse gráfico.',
      AppStrings.simulatedWalletSelectTypeError: 'Escolha o tipo do ativo',
      AppStrings.simulatedWalletTypeMismatchWarning: 'Esse ticker parece ser {detected}, não {selected}.',
      AppStrings.simulatedWalletEmptyStateTitle: 'Monte sua carteira simulada',
      AppStrings.simulatedWalletEmptyStateBody:
          'Adicione seu primeiro ativo e a data em que o compraria para acompanhar quanto você ganharia ou perderia de verdade.',
      AppStrings.simulatedWalletEmptyStateCta: 'Adicionar primeiro ativo',
      AppStrings.holdingQuoteUnavailable: 'sem cotação',
      AppStrings.holdingNotQuoted: 'não cotado',
      AppStrings.homeGreetingWithName: 'Bem-vindo de volta, {name}',
      AppStrings.homeStreakDaysLabel: '{days} dias',
      AppStrings.homeContinueGoalSubtitle: 'Baseado no seu objetivo: {goal}',
      AppStrings.homeContinueLearningEyebrow: 'Continue aprendendo',
      AppStrings.homeContinueLessonPosition: 'Aula {position} de {total}',
      AppStrings.homeCompanionLevelChip: 'Nível {level}',
      AppStrings.homeJourneySummaryLabel: 'SUA JORNADA',
      AppStrings.homeViewFullJourneyCta: 'Ver jornada completa',
      AppStrings.homeJourneyStagePosition: 'Escola {position} de {total}',
      AppStrings.homeJourneyNextStage: 'A seguir: {title}',
      AppStrings.homeJourneyCompleteTitle: 'Você percorreu toda a jornada disponível',
      AppStrings.homeJourneyCompleteStages: '{completed} de {total} etapas concluídas',
      AppStrings.homeMentorReasonContinue: 'Baseado na próxima aula disponível na sua trilha.',
      AppStrings.homeMentorReasonReview: 'Baseado em conceitos pendentes de revisão.',
      AppStrings.homeMentorReasonReturn: 'Baseado no tempo desde sua última visita.',
      AppStrings.homeMentorSourcesLabel: 'Por que recomendamos',
      AppStrings.homeMentorSourceContinue1: 'Próxima aula disponível',
      AppStrings.homeMentorSourceContinue2: 'Seu progresso na trilha atual',
      AppStrings.homeMentorSourceContinue3: 'Ordem das aulas na trilha',
      AppStrings.homeMentorSourceReview1: 'Aulas com desempenho baixo no quiz',
      AppStrings.homeMentorSourceReview2: 'Seu histórico de revisões',
      AppStrings.homeMentorSourceReview3: 'Revisão dos conceitos aprendidos',
      AppStrings.homeMentorSourceReturn1: 'Tempo desde sua última visita',
      AppStrings.homeMentorSourceReturn2: 'Sua trilha em andamento',
      AppStrings.homeMentorSourceReturn3: 'Retomada dos estudos',
      AppStrings.mentorHeaderTitle: 'Seu Mentor',
      AppStrings.mentorHeaderSubtitle: 'Tira dúvidas e explica conceitos — não é conselho financeiro',
      AppStrings.mentorStageGreeting: 'Oi, {name} 👋',
      AppStrings.mentorStageGreetingNoName: 'Oi 👋',
      AppStrings.mentorStageGreetingPrompt: 'O que vamos aprender hoje?',
      AppStrings.mentorStageThinkingTitle: 'Deixa eu pensar nisso...',
      AppStrings.mentorStageThinkingSubtitle: 'Só um segundo.',
      AppStrings.mentorStageAskSomethingElse: 'Perguntar outra coisa',
      AppStrings.mentorStageInputHint: 'Pergunte algo ao seu mentor...',
      AppStrings.labSimulatedDataBadge: 'Simulação — dados fictícios, não é sua carteira real',
      AppStrings.portfolioMilestoneUnlocked: 'Novo marco: {title}',

      AppStrings.petGoalEmergencyFund: 'Reserva de emergência',
      AppStrings.petGoalGetOutOfDebt: 'Sair das dívidas',
      AppStrings.petGoalBuyImportantThing: 'Comprar algo importante',
      AppStrings.petGoalInvestWithConfidence: 'Investir com confiança',
      AppStrings.petGoalJustWantToLearn: 'Só quero aprender',
      AppStrings.investmentHorizonUpToOneYear: 'Até 1 ano',
      AppStrings.investmentHorizonOneToFiveYears: '1 a 5 anos',
      AppStrings.investmentHorizonMoreThanFiveYears: 'Mais de 5 anos',
      AppStrings.investmentHorizonNotSureYet: 'Ainda não sei',
      AppStrings.experienceLevelNoviceLabel: 'Iniciante',
      AppStrings.experienceLevelCuriousLabel: 'Curioso',
      AppStrings.experienceLevelPractitionerLabel: 'Praticante',
      AppStrings.experienceLevelNoviceDescription: 'Nunca investi',
      AppStrings.experienceLevelCuriousDescription: 'Já ouvi falar, nunca pratiquei',
      AppStrings.experienceLevelPractitionerDescription: 'Já invisto, quero entender melhor',
      AppStrings.healthMetricDiversification: 'Diversificação',
      AppStrings.healthMetricGrowth: 'Crescimento',
      AppStrings.healthMetricIncomeStability: 'Estab. de Renda',
      AppStrings.healthMetricDividendStrength: 'Força de Dividendos',
      AppStrings.healthMetricVolatilityControl: 'Controle de Volatilidade',
      AppStrings.healthMetricLongTermPotential: 'Potencial Longo Prazo',
      AppStrings.achievementFirstInvestmentTitle: 'Primeiro Investimento',
      AppStrings.achievementFirstInvestmentDescription: 'Registrou seu primeiro ativo no portfólio.',
      AppStrings.achievementFirstDividendTitle: 'Primeiro Dividendo',
      AppStrings.achievementFirstDividendDescription: 'Possui ao menos um ativo com geração de renda passiva.',
      AppStrings.achievementPositiveReturnTitle: 'Primeiro Lucro',
      AppStrings.achievementPositiveReturnDescription: 'Seu portfólio atingiu retorno positivo.',
      AppStrings.achievementPortfolio10kTitle: 'Patamar de R\$10 mil',
      AppStrings.achievementPortfolio10kDescription: 'Alcançou R\$10.000 em patrimônio investido.',
      AppStrings.achievementPortfolio50kTitle: 'Patamar de R\$50 mil',
      AppStrings.achievementPortfolio50kDescription: 'Alcançou R\$50.000 em patrimônio investido.',
      AppStrings.achievementDiversificationMasterTitle: 'Mestre da Diversificação',
      AppStrings.achievementDiversificationMasterDescription: 'Investiu em 4 ou mais categorias de ativos.',
      AppStrings.achievementEtfCollectorTitle: 'Colecionador de ETFs',
      AppStrings.achievementEtfCollectorDescription: 'Reuniu 3 ou mais ETFs/fundos distintos.',
      AppStrings.achievementHundredDaysTitle: '100 Dias Investindo',
      AppStrings.achievementHundredDaysDescription: 'Manteve investimentos ativos por 100 dias.',
      AppStrings.achievementLongTermInvestorTitle: 'Investidor de Longo Prazo',
      AppStrings.achievementLongTermInvestorDescription: 'Manteve investimentos ativos por 1 ano.',
      AppStrings.achievementDividendHunterTitle: 'Caçador de Dividendos',
      AppStrings.achievementDividendHunterDescription: 'Alcançou R\$1.000/ano em renda passiva estimada.',
    },
    // Português europeu. Deliberadamente esparso: só as entradas que diferem
    // do pt-BR. Todo o resto resolve pelo fallback de [translate] para o bloco
    // 'pt', que aqui é o comportamento certo — as duas variantes partilham a
    // maior parte da língua, e uma chave em falta não é um buraco de tradução.
    // O teste 'pt_PT só define chaves que pt também define' impede órfãs.
    'pt_PT': {
      AppStrings.brandTagline: 'Aprenda a investir a jogar',
      AppStrings.gamificationIntroCompareRuleBody:
          'O seu progresso é só seu. Não existe ranking de património ou retorno aqui.',
    },
    'en': {
      AppStrings.profileProgressUnavailable: 'Could not load your progress. Reopen your profile to retry.',
      AppStrings.settingsSubtitle: 'Personalize your learning experience.',
      AppStrings.profileCommanderTitle: 'Your learning',
      AppStrings.appBarPlayerGenericGreeting: 'Level {level} · {tier}',
      AppStrings.companionAcademyContinueLesson: 'Your next lesson is "{lessonTitle}". Ready to learn?',
      AppStrings.companionAcademyReviewDue: 'You have {count} lessons to review. Shall we reinforce what you learned?',
      AppStrings.quizRetryInstruction: 'Tap the correct answer, marked in green, to continue.',
      AppStrings.homeStreakDaySingular: '{days} day',
      AppStrings.reviewDueSingular: 'You have 1 lesson to review. Shall we reinforce what you learned?',
      AppStrings.profileLearningProgress: '{count} lessons completed',
      AppStrings.profileLearningProgressOne: '1 lesson completed',
      AppStrings.profileLearningEmpty: 'Your journey starts with your first lesson.',
      AppStrings.profileXp: '{xp} XP earned',

      AppStrings.simulatedHoldingQuantityPrice: '{quantity} units · Avg {price}',
      AppStrings.simulatedHoldingAllocation: '{percent} of portfolio',

      AppStrings.academyRefreshError: 'Unable to refresh your data. Pull to refresh.',
      AppStrings.missionDailyLessonTitle: 'Lesson of the Day',
      AppStrings.missionDailyLessonDescription: 'Complete 1 lesson today.',
      AppStrings.missionDailyTwoTitle: 'Productive Day',
      AppStrings.missionDailyTwoDescription: 'Complete 2 lessons today.',
      AppStrings.missionWeeklyThreeTitle: 'Weekly Rhythm',
      AppStrings.missionWeeklyThreeDescription: 'Complete 3 lessons this week.',
      AppStrings.missionWeeklyModuleTitle: 'Module Complete',
      AppStrings.missionWeeklyModuleDescription: 'Complete an entire module this week.',
      AppStrings.investmentShortFixed: 'Fixed inc.',
      AppStrings.investmentShortRealEstate: 'RE funds',

      AppStrings.brandTitle: 'Petrimonium',
      AppStrings.brandTagline: 'Learn investing by playing',
      AppStrings.logoutConfirmTitle: 'Leave Petrimonium Academy?',
      AppStrings.createAccount: 'Create Account',
      AppStrings.fillDetails: 'Fill in your details',
      AppStrings.alreadyHaveAccount: 'Already have an account? Login',
      AppStrings.meetPetTitle: 'Name your journey partner',
      AppStrings.meetPetIntro: 'It grows with what you learn — never with how much you have.',
      AppStrings.financialGoalTitle: "What's your goal right now?",
      AppStrings.financialGoalSubtitle: 'This shapes your path. You can change it later.',
      AppStrings.welcomeHeadline: 'Learn finance by practicing, safely.',
      AppStrings.welcomeSubheadline: 'PETRIMONIUM ACADEMY',
      AppStrings.shareProgressCta: 'Download Petrimonium Academy and start your journey',
      AppStrings.inAppBrandName: 'Petrimonium Academy',
      AppStrings.academyIntroTitle: 'Your track starts here',
      AppStrings.academyIntroSubtitle: 'A suggested order — you choose where to start.',
      AppStrings.academyIntroStartsNow: 'starts now',
      AppStrings.academyIntroMentorIntro: "Let's start with {module}. {count} — you can do it now.",
      AppStrings.academyIntroLessonSingular: 'lesson',
      AppStrings.academyIntroLessonPlural: 'lessons',
      AppStrings.academyIntroMoreSchools: '{count} more {unit} on the track.',
      AppStrings.academyIntroSchoolSingular: 'school',
      AppStrings.academyIntroSchoolPlural: 'schools',
      AppStrings.gamificationIntroTitle: 'How you progress here',
      AppStrings.gamificationIntroXpRuleTitle: 'XP for learning',
      AppStrings.gamificationIntroXpRuleBody:
          'You earn XP by completing lessons and practice — never for returns, deposits, or trades.',
      AppStrings.gamificationIntroStreakRuleTitle: 'No-punishment streak',
      AppStrings.gamificationIntroStreakRuleBody:
          "Missing a day doesn't reset your progress or penalize you — your pet just misses you.",
      AppStrings.gamificationIntroCompareRuleTitle: 'No comparing with others',
      AppStrings.gamificationIntroCompareRuleBody:
          "Your progress is yours alone. There's no net worth or returns leaderboard here.",
      AppStrings.timeHorizonTitle: 'When is this goal for?',
      AppStrings.timeHorizonSubtitle: "Not sure? That's fine, it's just a starting point.",
      AppStrings.experienceLevelTitle: "How's your experience today?",
      AppStrings.experienceLevelSubtitle: "This way the Academy won't teach you what you already know.",
      AppStrings.academyLessonCompleteTitle: 'Lesson complete!',
      AppStrings.academyLearningProgressPill: '+{xp} XP · learning progress',
      AppStrings.academyContentLabel: 'EDUCATIONAL CONTENT',
      AppStrings.academyExampleLabel: 'EXAMPLE',
      AppStrings.academyLessonOfLabel: 'Lesson {n} of {total}',
      AppStrings.mentorInterpretationLabel: 'MENTOR · AI INTERPRETATION',
      AppStrings.academyAllModulesTitle: 'Your full track',
      AppStrings.academyJourneySubtitle: 'Your investing journey',
      AppStrings.academyJourneyExploreTooltip: 'See the full track',
      AppStrings.academyJourneyYouAreHere: "You're here",
      AppStrings.academyJourneyUpNext: 'Up next',
      AppStrings.academyJourneyContinueLesson: 'Continue lesson',
      AppStrings.academyJourneyStageProgress: '{completed} of {total} lessons',
      AppStrings.academyJourneyStageCompleted: '{completed}/{total} done',
      AppStrings.academyJourneyStageTotalLessons: '{total} lessons',
      AppStrings.academyJourneyStageNotStarted: '{total} lessons · not started yet',
      AppStrings.academyJourneyModuleProgress: '{completed}/{total} lessons',
      AppStrings.academyJourneyBadgeInProgress: 'in progress',
      AppStrings.academyJourneyLessonMinutes: '~{minutes} min',
      AppStrings.walletBridgeCtaLabel: 'See this in your real portfolio',
      AppStrings.walletBridgeComingSoon: 'Coming soon in Wallet',
      AppStrings.simulatedWalletTitle: 'Simulated Wallet',
      AppStrings.simulatedWalletDisclaimer:
          'Simulation wallet: you enter the assets and dates, and quotes are real. No order is executed and there is no connection to any exchange, broker, or bank. Not financial advice — simulated results do not guarantee real results.',
      AppStrings.simulatedWalletNoPositions:
          "You don't have any simulated positions yet. How about placing your first order?",
      AppStrings.simulatedWalletResetAction: 'Reset simulation',
      AppStrings.simulatedWalletResetConfirmTitle: 'Reset simulation?',
      AppStrings.simulatedWalletResetConfirmMessage:
          'This erases every simulated position and order. This cannot be undone.',
      AppStrings.simulatedWalletResetConfirmAction: 'Reset',
      AppStrings.simulatedWalletResetSuccess: 'Simulation reset',
      AppStrings.simulatedOrderScreenTitle: 'New simulated order',
      AppStrings.simulatedOrderSearchHint: 'Search an asset (e.g. PETR4)',
      AppStrings.simulatedOrderBuyLabel: 'Buy',
      AppStrings.simulatedOrderSellLabel: 'Sell',
      AppStrings.simulatedOrderQuantityLabel: 'Quantity',
      AppStrings.simulatedOrderReferencePriceLabel: 'Reference price (simulated)',
      AppStrings.simulatedOrderConfirmAction: 'Confirm simulated order',
      AppStrings.simulatedOrderSuccessMessage: 'Simulated order placed',
      AppStrings.simulatedOrderSelectAssetFirst: 'Search and select an asset first',
      AppStrings.simulatedOrderDateLabel: 'Order date',
      AppStrings.simulatedOrderDateToday: 'Today',
      AppStrings.simulatedOrderHistoricalPriceLabel: 'Closing price on',
      AppStrings.simulatedOrderNoHistoricalQuote: 'No quote available for this date',
      AppStrings.simulatedWalletAllocationTitle: 'Simulated allocation',
      AppStrings.simulatedWalletTotalPatrimonyLabel: 'Total simulated patrimony',
      AppStrings.simulatedWalletResultLabel: 'Result',
      AppStrings.simulatedWalletReturnLabel: 'Return on invested',
      AppStrings.simulatedWalletPriceUnavailable: 'Price unavailable',
      AppStrings.simulatedWalletHeaderSubtitle: 'Practice investing, with no real money',
      AppStrings.simulatedWalletAddAssetLabel: 'Add',
      AppStrings.simulatedWalletMyAssetsLabel: 'MY SIMULATED ASSETS',
      AppStrings.simulatedWalletAllocationEmpty: "There isn't enough data to work out your allocation.",
      AppStrings.simulatedWalletAllocationCenterLabel: 'TOTAL',
      AppStrings.simulatedWalletWealthBarsTitle: 'Simulated wealth evolution',
      AppStrings.simulatedWalletWealthBarsRangeChip: '12 months',
      AppStrings.simulatedWalletWealthBarsLegendInvested: 'Invested capital',
      AppStrings.simulatedWalletWealthBarsLegendGain: 'Capital gain',
      AppStrings.simulatedWalletWealthBarsLegendShortfall: 'Below invested',
      AppStrings.simulatedWalletWealthBarsEmpty: "There isn't enough history yet to draw this chart.",
      AppStrings.simulatedWalletSelectTypeError: 'Pick the asset type',
      AppStrings.simulatedWalletTypeMismatchWarning: 'That ticker looks like {detected}, not {selected}.',
      AppStrings.simulatedWalletEmptyStateTitle: 'Build your simulated portfolio',
      AppStrings.simulatedWalletEmptyStateBody:
          'Add your first asset and the date you would have bought it to track how much you would really gain or lose.',
      AppStrings.simulatedWalletEmptyStateCta: 'Add first asset',
      AppStrings.holdingQuoteUnavailable: 'no quote',
      AppStrings.holdingNotQuoted: 'not quoted',
      AppStrings.homeContinueLearningEyebrow: 'Keep learning',
      AppStrings.homeContinueLessonPosition: 'Lesson {position} of {total}',
      AppStrings.homeCompanionLevelChip: 'Level {level}',
      AppStrings.homeJourneySummaryLabel: 'YOUR JOURNEY',
      AppStrings.homeViewFullJourneyCta: 'See full journey',
      AppStrings.homeJourneyStagePosition: 'School {position} of {total}',
      AppStrings.homeJourneyNextStage: 'Up next: {title}',
      AppStrings.homeJourneyCompleteTitle: "You've walked the whole journey available",
      AppStrings.homeJourneyCompleteStages: '{completed} of {total} stages done',
      AppStrings.homeGreetingWithName: 'Welcome back, {name}',
      AppStrings.homeStreakDaysLabel: '{days} days',
      AppStrings.homeContinueGoalSubtitle: 'Based on your goal: {goal}',
      AppStrings.homeMentorReasonContinue: 'Based on the next available lesson on your path.',
      AppStrings.homeMentorReasonReview: 'Based on concepts due for review.',
      AppStrings.homeMentorReasonReturn: "Based on how long it's been since your last visit.",
      AppStrings.homeMentorSourcesLabel: 'Why we recommend this',
      AppStrings.homeMentorSourceContinue1: 'Next available lesson',
      AppStrings.homeMentorSourceContinue2: 'Your progress on the current path',
      AppStrings.homeMentorSourceContinue3: 'Lesson order on your path',
      AppStrings.homeMentorSourceReview1: 'Lessons with low quiz performance',
      AppStrings.homeMentorSourceReview2: 'Your review history',
      AppStrings.homeMentorSourceReview3: 'Review of learned concepts',
      AppStrings.homeMentorSourceReturn1: 'Time since your last visit',
      AppStrings.homeMentorSourceReturn2: 'Your path in progress',
      AppStrings.homeMentorSourceReturn3: 'Returning to learning',
      AppStrings.mentorHeaderTitle: 'Your Mentor',
      AppStrings.mentorHeaderSubtitle: 'Answers questions and explains concepts — not financial advice',
      AppStrings.mentorStageGreeting: 'Hi, {name} 👋',
      AppStrings.mentorStageGreetingNoName: 'Hi 👋',
      AppStrings.mentorStageGreetingPrompt: 'What shall we learn today?',
      AppStrings.mentorStageThinkingTitle: 'Let me think about that...',
      AppStrings.mentorStageThinkingSubtitle: 'Just a second.',
      AppStrings.mentorStageAskSomethingElse: 'Ask something else',
      AppStrings.mentorStageInputHint: 'Ask your mentor something...',
      AppStrings.labSimulatedDataBadge: 'Simulation — fictional data, not your real portfolio',
      AppStrings.portfolioMilestoneUnlocked: 'New milestone: {title}',

      AppStrings.petGoalEmergencyFund: 'Emergency fund',
      AppStrings.petGoalGetOutOfDebt: 'Get out of debt',
      AppStrings.petGoalBuyImportantThing: 'Buy something important',
      AppStrings.petGoalInvestWithConfidence: 'Invest with confidence',
      AppStrings.petGoalJustWantToLearn: 'Just want to learn',
      AppStrings.investmentHorizonUpToOneYear: 'Up to 1 year',
      AppStrings.investmentHorizonOneToFiveYears: '1 to 5 years',
      AppStrings.investmentHorizonMoreThanFiveYears: 'More than 5 years',
      AppStrings.investmentHorizonNotSureYet: 'Not sure yet',
      AppStrings.experienceLevelNoviceLabel: 'Novice',
      AppStrings.experienceLevelCuriousLabel: 'Curious',
      AppStrings.experienceLevelPractitionerLabel: 'Practitioner',
      AppStrings.experienceLevelNoviceDescription: 'Never invested',
      AppStrings.experienceLevelCuriousDescription: "I've heard of it, never tried",
      AppStrings.experienceLevelPractitionerDescription: 'I already invest, want to understand better',
      AppStrings.healthMetricDiversification: 'Diversification',
      AppStrings.healthMetricGrowth: 'Growth',
      AppStrings.healthMetricIncomeStability: 'Income Stability',
      AppStrings.healthMetricDividendStrength: 'Dividend Strength',
      AppStrings.healthMetricVolatilityControl: 'Volatility Control',
      AppStrings.healthMetricLongTermPotential: 'Long-Term Potential',
      AppStrings.achievementFirstInvestmentTitle: 'First Investment',
      AppStrings.achievementFirstInvestmentDescription: 'Registered your first asset in the portfolio.',
      AppStrings.achievementFirstDividendTitle: 'First Dividend',
      AppStrings.achievementFirstDividendDescription: 'Holds at least one asset that generates passive income.',
      AppStrings.achievementPositiveReturnTitle: 'First Profit',
      AppStrings.achievementPositiveReturnDescription: 'Your portfolio reached a positive return.',
      AppStrings.achievementPortfolio10kTitle: 'R\$10k Milestone',
      AppStrings.achievementPortfolio10kDescription: 'Reached R\$10,000 in invested wealth.',
      AppStrings.achievementPortfolio50kTitle: 'R\$50k Milestone',
      AppStrings.achievementPortfolio50kDescription: 'Reached R\$50,000 in invested wealth.',
      AppStrings.achievementDiversificationMasterTitle: 'Diversification Master',
      AppStrings.achievementDiversificationMasterDescription: 'Invested in 4 or more asset categories.',
      AppStrings.achievementEtfCollectorTitle: 'ETF Collector',
      AppStrings.achievementEtfCollectorDescription: 'Gathered 3 or more distinct ETFs/funds.',
      AppStrings.achievementHundredDaysTitle: '100 Days Investing',
      AppStrings.achievementHundredDaysDescription: 'Kept active investments for 100 days.',
      AppStrings.achievementLongTermInvestorTitle: 'Long-Term Investor',
      AppStrings.achievementLongTermInvestorDescription: 'Kept active investments for 1 year.',
      AppStrings.achievementDividendHunterTitle: 'Dividend Hunter',
      AppStrings.achievementDividendHunterDescription: 'Reached R\$1,000/year in estimated passive income.',
    },
    'es': {
      AppStrings.profileProgressUnavailable: 'No se pudo cargar tu progreso. Vuelve a abrir tu perfil para intentarlo.',
      AppStrings.settingsSubtitle: 'Personaliza tu experiencia de aprendizaje.',
      AppStrings.profileCommanderTitle: 'Tu aprendizaje',
      AppStrings.appBarPlayerGenericGreeting: 'Nivel {level} · {tier}',
      AppStrings.companionAcademyContinueLesson: 'Tu próxima lección es "{lessonTitle}". ¿Aprendemos?',
      AppStrings.companionAcademyReviewDue: 'Tienes {count} lecciones para repasar. ¿Reforzamos lo aprendido?',
      AppStrings.quizRetryInstruction: 'Toca la respuesta correcta, marcada en verde, para continuar.',
      AppStrings.homeStreakDaySingular: '{days} día',
      AppStrings.reviewDueSingular: 'Tienes 1 lección para repasar. ¿Reforzamos lo aprendido?',
      AppStrings.profileLearningProgress: '{count} lecciones completadas',
      AppStrings.profileLearningProgressOne: '1 lección completada',
      AppStrings.profileLearningEmpty: 'Tu camino empieza con la primera lección.',
      AppStrings.profileXp: '{xp} XP ganados',

      AppStrings.simulatedHoldingQuantityPrice: '{quantity} un · PM {price}',
      AppStrings.simulatedHoldingAllocation: '{percent} de la cartera',

      AppStrings.academyRefreshError: 'No se pudieron actualizar tus datos. Desliza para actualizar.',
      AppStrings.missionDailyLessonTitle: 'Lección del día',
      AppStrings.missionDailyLessonDescription: 'Completa 1 lección hoy.',
      AppStrings.missionDailyTwoTitle: 'Día productivo',
      AppStrings.missionDailyTwoDescription: 'Completa 2 lecciones hoy.',
      AppStrings.missionWeeklyThreeTitle: 'Ritmo semanal',
      AppStrings.missionWeeklyThreeDescription: 'Completa 3 lecciones esta semana.',
      AppStrings.missionWeeklyModuleTitle: 'Módulo completo',
      AppStrings.missionWeeklyModuleDescription: 'Completa un módulo entero esta semana.',
      AppStrings.investmentShortFixed: 'R. fija',
      AppStrings.investmentShortRealEstate: 'F. inmob.',

      AppStrings.brandTitle: 'Petrimonium',
      AppStrings.brandTagline: 'Aprende a invertir jugando',
      AppStrings.logoutConfirmTitle: '¿Salir de Petrimonium Academy?',
      AppStrings.createAccount: 'Crear Cuenta',
      AppStrings.fillDetails: 'Completa tus datos',
      AppStrings.alreadyHaveAccount: '¿Ya tienes cuenta? Entrar',
      AppStrings.meetPetTitle: 'Ponle nombre a tu compañero de viaje',
      AppStrings.meetPetIntro: 'Evoluciona con lo que aprendes — nunca con cuánto tienes.',
      AppStrings.financialGoalTitle: '¿Cuál es tu objetivo ahora?',
      AppStrings.financialGoalSubtitle: 'Esto ajusta tu camino. Puedes cambiarlo después.',
      AppStrings.welcomeHeadline: 'Aprende finanzas practicando con seguridad.',
      AppStrings.welcomeSubheadline: 'PETRIMONIUM ACADEMY',
      AppStrings.shareProgressCta: 'Descarga Petrimonium Academy y comienza tu viaje',
      AppStrings.inAppBrandName: 'Petrimonium Academy',
      AppStrings.academyIntroTitle: 'Tu camino comienza aquí',
      AppStrings.academyIntroSubtitle: 'Un orden sugerido — tú eliges por dónde empezar.',
      AppStrings.academyIntroStartsNow: 'empieza ahora',
      AppStrings.academyIntroMentorIntro: 'Empecemos por {module}. {count} — puedes hacerlo ahora.',
      AppStrings.academyIntroLessonSingular: 'lección',
      AppStrings.academyIntroLessonPlural: 'lecciones',
      AppStrings.academyIntroMoreSchools: '{count} {unit} más en el camino.',
      AppStrings.academyIntroSchoolSingular: 'escuela',
      AppStrings.academyIntroSchoolPlural: 'escuelas',
      AppStrings.gamificationIntroTitle: 'Cómo progresas aquí',
      AppStrings.gamificationIntroXpRuleTitle: 'XP por aprender',
      AppStrings.gamificationIntroXpRuleBody:
          'Ganas XP completando lecciones y prácticas — nunca por valorización, aportes u operaciones.',
      AppStrings.gamificationIntroStreakRuleTitle: 'Racha sin penalización',
      AppStrings.gamificationIntroStreakRuleBody:
          'Perder un día no reinicia tu progreso ni te penaliza — tu mascota solo te extraña.',
      AppStrings.gamificationIntroCompareRuleTitle: 'Sin comparación entre personas',
      AppStrings.gamificationIntroCompareRuleBody:
          'Tu progreso es solo tuyo. Aquí no existe un ranking de patrimonio ni de rentabilidad.',
      AppStrings.timeHorizonTitle: '¿Para cuándo es ese objetivo?',
      AppStrings.timeHorizonSubtitle: '¿No estás seguro? Está bien, es solo un punto de partida.',
      AppStrings.experienceLevelTitle: '¿Cómo está tu experiencia hoy?',
      AppStrings.experienceLevelSubtitle: 'Así la Academy no te enseña lo que ya sabes.',
      AppStrings.academyLessonCompleteTitle: '¡Lección completada!',
      AppStrings.academyLearningProgressPill: '+{xp} XP · progreso de aprendizaje',
      AppStrings.academyContentLabel: 'CONTENIDO EDUCATIVO',
      AppStrings.academyExampleLabel: 'EJEMPLO',
      AppStrings.academyLessonOfLabel: 'Lección {n} de {total}',
      AppStrings.mentorInterpretationLabel: 'MENTOR · INTERPRETACIÓN DE IA',
      AppStrings.academyAllModulesTitle: 'Tu ruta completa',
      AppStrings.academyJourneySubtitle: 'Tu recorrido de inversiones',
      AppStrings.academyJourneyExploreTooltip: 'Ver la ruta completa',
      AppStrings.academyJourneyYouAreHere: 'Estás aquí',
      AppStrings.academyJourneyUpNext: 'A continuación',
      AppStrings.academyJourneyContinueLesson: 'Continuar lección',
      AppStrings.academyJourneyStageProgress: '{completed} de {total} lecciones',
      AppStrings.academyJourneyStageCompleted: '{completed}/{total} completadas',
      AppStrings.academyJourneyStageTotalLessons: '{total} lecciones',
      AppStrings.academyJourneyStageNotStarted: '{total} lecciones · aún sin empezar',
      AppStrings.academyJourneyModuleProgress: '{completed}/{total} lecciones',
      AppStrings.academyJourneyBadgeInProgress: 'en curso',
      AppStrings.academyJourneyLessonMinutes: '~{minutes} min',
      AppStrings.walletBridgeCtaLabel: 'Ver esto en tu cartera real',
      AppStrings.walletBridgeComingSoon: 'Próximamente en Wallet',
      AppStrings.simulatedWalletTitle: 'Cartera Simulada',
      AppStrings.simulatedWalletDisclaimer:
          'Cartera de simulación: tú indicas los activos y las fechas, y las cotizaciones son reales. No se ejecuta ninguna orden y no hay conexión con ninguna bolsa, corredora o banco. No es una recomendación financiera — los resultados simulados no garantizan resultados reales.',
      AppStrings.simulatedWalletNoPositions:
          'Aún no tienes posiciones simuladas. ¿Qué tal registrar tu primera operación?',
      AppStrings.simulatedWalletResetAction: 'Reiniciar simulación',
      AppStrings.simulatedWalletResetConfirmTitle: '¿Reiniciar simulación?',
      AppStrings.simulatedWalletResetConfirmMessage:
          'Esto borra todas las posiciones y operaciones simuladas. Esta acción no se puede deshacer.',
      AppStrings.simulatedWalletResetConfirmAction: 'Reiniciar',
      AppStrings.simulatedWalletResetSuccess: 'Simulación reiniciada',
      AppStrings.simulatedOrderScreenTitle: 'Nueva operación simulada',
      AppStrings.simulatedOrderSearchHint: 'Buscar activo (ej: PETR4)',
      AppStrings.simulatedOrderBuyLabel: 'Comprar',
      AppStrings.simulatedOrderSellLabel: 'Vender',
      AppStrings.simulatedOrderQuantityLabel: 'Cantidad',
      AppStrings.simulatedOrderReferencePriceLabel: 'Precio de referencia (simulado)',
      AppStrings.simulatedOrderConfirmAction: 'Confirmar operación simulada',
      AppStrings.simulatedOrderSuccessMessage: 'Operación simulada registrada',
      AppStrings.simulatedOrderSelectAssetFirst: 'Busca y selecciona un activo primero',
      AppStrings.simulatedOrderDateLabel: 'Fecha de la operación',
      AppStrings.simulatedOrderDateToday: 'Hoy',
      AppStrings.simulatedOrderHistoricalPriceLabel: 'Precio de cierre del',
      AppStrings.simulatedOrderNoHistoricalQuote: 'Sin cotización disponible para esta fecha',
      AppStrings.simulatedWalletAllocationTitle: 'Asignación simulada',
      AppStrings.simulatedWalletTotalPatrimonyLabel: 'Patrimonio total simulado',
      AppStrings.simulatedWalletResultLabel: 'Resultado',
      AppStrings.simulatedWalletReturnLabel: 'Retorno sobre lo invertido',
      AppStrings.simulatedWalletPriceUnavailable: 'Precio no disponible',
      AppStrings.simulatedWalletHeaderSubtitle: 'Practica invertir, sin dinero real',
      AppStrings.simulatedWalletAddAssetLabel: 'Agregar',
      AppStrings.simulatedWalletMyAssetsLabel: 'MIS ACTIVOS SIMULADOS',
      AppStrings.simulatedWalletAllocationEmpty: 'No hay suficientes datos para calcular tu asignación.',
      AppStrings.simulatedWalletAllocationCenterLabel: 'TOTAL',
      AppStrings.simulatedWalletWealthBarsTitle: 'Evolución del patrimonio simulado',
      AppStrings.simulatedWalletWealthBarsRangeChip: '12 meses',
      AppStrings.simulatedWalletWealthBarsLegendInvested: 'Valor aplicado',
      AppStrings.simulatedWalletWealthBarsLegendGain: 'Ganancia de capital',
      AppStrings.simulatedWalletWealthBarsLegendShortfall: 'Por debajo de lo aplicado',
      AppStrings.simulatedWalletWealthBarsEmpty: 'Todavía no hay suficiente historial para armar este gráfico.',
      AppStrings.simulatedWalletSelectTypeError: 'Elige el tipo de activo',
      AppStrings.simulatedWalletTypeMismatchWarning: 'Ese ticker parece ser {detected}, no {selected}.',
      AppStrings.simulatedWalletEmptyStateTitle: 'Arma tu cartera simulada',
      AppStrings.simulatedWalletEmptyStateBody:
          'Agrega tu primer activo y la fecha en que lo comprarías para ver cuánto ganarías o perderías de verdad.',
      AppStrings.simulatedWalletEmptyStateCta: 'Agregar primer activo',
      AppStrings.holdingQuoteUnavailable: 'sin cotización',
      AppStrings.holdingNotQuoted: 'no cotizado',
      AppStrings.homeContinueLearningEyebrow: 'Sigue aprendiendo',
      AppStrings.homeContinueLessonPosition: 'Lección {position} de {total}',
      AppStrings.homeCompanionLevelChip: 'Nivel {level}',
      AppStrings.homeJourneySummaryLabel: 'TU RECORRIDO',
      AppStrings.homeViewFullJourneyCta: 'Ver recorrido completo',
      AppStrings.homeJourneyStagePosition: 'Escuela {position} de {total}',
      AppStrings.homeJourneyNextStage: 'A continuación: {title}',
      AppStrings.homeJourneyCompleteTitle: 'Recorriste todo el camino disponible',
      AppStrings.homeJourneyCompleteStages: '{completed} de {total} etapas completadas',
      AppStrings.homeGreetingWithName: 'Bienvenido de nuevo, {name}',
      AppStrings.homeStreakDaysLabel: '{days} días',
      AppStrings.homeContinueGoalSubtitle: 'Basado en tu objetivo: {goal}',
      AppStrings.homeMentorWhySeeing: '¿Por qué estoy viendo esto?',
      AppStrings.homeMentorReasonContinue: 'Basado en la próxima lección disponible en tu ruta.',
      AppStrings.homeMentorReasonReview: 'Basado en conceptos pendientes de repaso.',
      AppStrings.homeMentorReasonReturn: 'Basado en el tiempo desde tu última visita.',
      AppStrings.homeMentorSourcesLabel: 'Por qué lo recomendamos',
      AppStrings.homeMentorSourceContinue1: 'Próxima lección disponible',
      AppStrings.homeMentorSourceContinue2: 'Tu progreso en la ruta actual',
      AppStrings.homeMentorSourceContinue3: 'Orden de las lecciones en tu ruta',
      AppStrings.homeMentorSourceReview1: 'Lecciones con bajo desempeño en el quiz',
      AppStrings.homeMentorSourceReview2: 'Tu historial de repasos',
      AppStrings.homeMentorSourceReview3: 'Repaso de conceptos aprendidos',
      AppStrings.homeMentorSourceReturn1: 'Tiempo desde tu última visita',
      AppStrings.homeMentorSourceReturn2: 'Tu ruta en curso',
      AppStrings.homeMentorSourceReturn3: 'Retomar el aprendizaje',
      AppStrings.mentorHeaderTitle: 'Tu Mentor',
      AppStrings.mentorHeaderSubtitle: 'Responde dudas y explica conceptos — no es asesoría financiera',
      AppStrings.mentorStageGreeting: 'Hola, {name} 👋',
      AppStrings.mentorStageGreetingNoName: 'Hola 👋',
      AppStrings.mentorStageGreetingPrompt: '¿Qué vamos a aprender hoy?',
      AppStrings.mentorStageThinkingTitle: 'Déjame pensar en eso...',
      AppStrings.mentorStageThinkingSubtitle: 'Solo un segundo.',
      AppStrings.mentorStageAskSomethingElse: 'Preguntar otra cosa',
      AppStrings.mentorStageInputHint: 'Pregúntale algo a tu mentor...',
      AppStrings.labSimulatedDataBadge: 'Simulación — datos ficticios, no es tu cartera real',
      AppStrings.portfolioMilestoneUnlocked: 'Nuevo hito: {title}',

      AppStrings.petGoalEmergencyFund: 'Fondo de emergencia',
      AppStrings.petGoalGetOutOfDebt: 'Salir de deudas',
      AppStrings.petGoalBuyImportantThing: 'Comprar algo importante',
      AppStrings.petGoalInvestWithConfidence: 'Invertir con confianza',
      AppStrings.petGoalJustWantToLearn: 'Solo quiero aprender',
      AppStrings.investmentHorizonUpToOneYear: 'Hasta 1 año',
      AppStrings.investmentHorizonOneToFiveYears: '1 a 5 años',
      AppStrings.investmentHorizonMoreThanFiveYears: 'Más de 5 años',
      AppStrings.investmentHorizonNotSureYet: 'Aún no lo sé',
      AppStrings.experienceLevelNoviceLabel: 'Principiante',
      AppStrings.experienceLevelCuriousLabel: 'Curioso',
      AppStrings.experienceLevelPractitionerLabel: 'Practicante',
      AppStrings.experienceLevelNoviceDescription: 'Nunca invertí',
      AppStrings.experienceLevelCuriousDescription: 'Ya escuché hablar de eso, nunca lo practiqué',
      AppStrings.experienceLevelPractitionerDescription: 'Ya invierto, quiero entender mejor',
      AppStrings.healthMetricDiversification: 'Diversificación',
      AppStrings.healthMetricGrowth: 'Crecimiento',
      AppStrings.healthMetricIncomeStability: 'Estab. de Ingresos',
      AppStrings.healthMetricDividendStrength: 'Fuerza de Dividendos',
      AppStrings.healthMetricVolatilityControl: 'Control de Volatilidad',
      AppStrings.healthMetricLongTermPotential: 'Potencial a Largo Plazo',
      AppStrings.achievementFirstInvestmentTitle: 'Primera Inversión',
      AppStrings.achievementFirstInvestmentDescription: 'Registró su primer activo en la cartera.',
      AppStrings.achievementFirstDividendTitle: 'Primer Dividendo',
      AppStrings.achievementFirstDividendDescription: 'Posee al menos un activo con generación de ingresos pasivos.',
      AppStrings.achievementPositiveReturnTitle: 'Primera Ganancia',
      AppStrings.achievementPositiveReturnDescription: 'Su cartera alcanzó un retorno positivo.',
      AppStrings.achievementPortfolio10kTitle: 'Hito de R\$10 mil',
      AppStrings.achievementPortfolio10kDescription: 'Alcanzó R\$10.000 en patrimonio invertido.',
      AppStrings.achievementPortfolio50kTitle: 'Hito de R\$50 mil',
      AppStrings.achievementPortfolio50kDescription: 'Alcanzó R\$50.000 en patrimonio invertido.',
      AppStrings.achievementDiversificationMasterTitle: 'Maestro de la Diversificación',
      AppStrings.achievementDiversificationMasterDescription: 'Invirtió en 4 o más categorías de activos.',
      AppStrings.achievementEtfCollectorTitle: 'Coleccionista de ETFs',
      AppStrings.achievementEtfCollectorDescription: 'Reunió 3 o más ETFs/fondos distintos.',
      AppStrings.achievementHundredDaysTitle: '100 Días Invirtiendo',
      AppStrings.achievementHundredDaysDescription: 'Mantuvo inversiones activas por 100 días.',
      AppStrings.achievementLongTermInvestorTitle: 'Inversor a Largo Plazo',
      AppStrings.achievementLongTermInvestorDescription: 'Mantuvo inversiones activas por 1 año.',
      AppStrings.achievementDividendHunterTitle: 'Cazador de Dividendos',
      AppStrings.achievementDividendHunterDescription: 'Alcanzó R\$1.000/año en ingresos pasivos estimados.',
    },
  };
}
