import 'package:flutter/foundation.dart';
import 'package:petrimonium_flutter_core/petrimonium_flutter_core.dart';
import 'package:petrimonium_shared_features/petrimonium_shared_features.dart';

import '../constants/app_strings.dart';

/// App-wide translator. pt-BR is the product's default language; en/es are
/// offered through the Settings screen.
///
/// The lookup itself lives in [TranslatorEngine]; this class is the product's
/// half of it. Copy every Petrimonium product words the same way comes from
/// `sharedCopy`; what stays here is only what this product says differently -
/// its brand voice, and the screens the other products do not have. Adding a
/// string that the sibling app already words identically belongs in
/// `sharedCopy`, not here.
///
/// The static surface is unchanged on purpose: 601 call sites already say
/// `Translator.translate(AppStrings.x)`, and none of them had to move.
class Translator {
  Translator._();

  static const String defaultLanguage = 'pt';
  static const Set<String> supportedLanguages = {'pt', 'pt_PT', 'en', 'es'};

  static final TranslatorEngine _engine = TranslatorEngine(
    base: sharedCopy,
    overrides: _productCopy,
    defaultLanguage: defaultLanguage,
    supportedLanguages: supportedLanguages,
  );

  static ValueNotifier<String> get languageNotifier => _engine.languageNotifier;

  static String get currentLanguage => _engine.currentLanguage;

  /// Synchronous setter kept for tests and simple in-memory switches.
  /// Prefer [setLanguage] in the app so the preference is persisted.
  static set currentLanguage(String language) => _engine.currentLanguage = language;

  /// Loads the persisted language preference. Call once during app startup,
  /// before the first screen is built.
  static Future<void> load() => _engine.load();

  /// Updates the current language and persists it locally.
  /// Does not call the backend — callers that need the preference synced
  /// server-side (e.g. the Settings screen) should do that separately.
  static Future<void> setLanguage(String language) => _engine.setLanguage(language);

  /// [params] fills `{token}` placeholders in the translated string (e.g.
  /// `{petName}`) — used for copy that embeds the user's chosen pet name,
  /// which can't be baked into the static translation map.
  static String translate(String key, {Map<String, String>? params}) => _engine.translate(key, params: params);

  /// Test-only escape hatch onto the *merged* catalogue (shared + product), so
  /// `translator_test.dart` keeps asserting parity over exactly what the app
  /// resolves at runtime, not over this file alone.
  static Map<String, Map<String, String>> get debugLocalizedValues => _engine.debugLocalizedValues;

  /// Test-only view of just this product's half, so a test can assert the
  /// halves stay disjoint — see `translator_test.dart`.
  static Map<String, Map<String, String>> get debugProductCopy => _productCopy;

  /// This product's own wording. Everything else comes from `sharedCopy`.
  static const Map<String, Map<String, String>> _productCopy = {
    'pt': {
      AppStrings.brandTitle: 'Petrimonium',
      AppStrings.brandTagline: 'Aprenda a investir jogando',
      AppStrings.logoutConfirmTitle: 'Sair do Petrimonium Academy?',
      AppStrings.createAccount: 'Criar Conta',
      AppStrings.fillDetails: 'Preencha seus dados',
      AppStrings.alreadyHaveAccount: 'Já tem conta? Entrar',
      AppStrings.meetPetTitle: 'Escolha seu parceiro de jornada',
      AppStrings.meetPetIntro: 'Ele evolui com o que você aprende — nunca com quanto você tem.',
      AppStrings.financialGoalTitle: 'Qual é o seu objetivo agora?',
      AppStrings.financialGoalSubtitle: 'Isso ajusta sua trilha. Você pode mudar depois.',
      AppStrings.welcomeHeadline: 'Aprenda finanças praticando com segurança.',
      AppStrings.welcomeSubheadline: 'PETRIMONIUM ACADEMY',
      AppStrings.shareProgressCta: 'Baixe o Petrimonium Academy e comece sua jornada',
      AppStrings.inAppBrandName: 'Petrimonium Academy',
      AppStrings.academyIntroTitle: 'Sua trilha começa aqui',
      AppStrings.academyIntroSubtitle: 'O resto libera conforme você avança — sem pular etapas.',
      AppStrings.academyIntroStartsNow: 'começa agora',
      AppStrings.academyIntroMentorIntro: 'Vamos começar por {module}. {count} — dá pra começar agora.',
      AppStrings.academyIntroLessonSingular: 'aula',
      AppStrings.academyIntroLessonPlural: 'aulas',
      AppStrings.gamificationIntroTitle: 'Como você progride aqui',
      AppStrings.gamificationIntroXpRuleTitle: 'XP por aprender',
      AppStrings.gamificationIntroXpRuleBody:
          'Você ganha XP completando aulas e práticas — nunca por valorização, aporte ou operação.',
      AppStrings.gamificationIntroStreakRuleTitle: 'Ofensiva sem punição',
      AppStrings.gamificationIntroStreakRuleBody:
          'Perder um dia não zera seu progresso nem te penaliza — o pet só fica com saudade.',
      AppStrings.gamificationIntroCompareRuleTitle: 'Sem comparação entre pessoas',
      AppStrings.gamificationIntroCompareRuleBody:
          'Seu progresso é só seu. Não existe ranking de patrimônio ou retorno aqui.',
      AppStrings.timeHorizonTitle: 'Para quando é esse objetivo?',
      AppStrings.timeHorizonSubtitle: 'Sem certeza? Tudo bem, é só um ponto de partida.',
      AppStrings.experienceLevelTitle: 'Como está sua experiência hoje?',
      AppStrings.experienceLevelSubtitle: 'Assim a Academy não te ensina o que você já sabe.',
      AppStrings.academyLessonCompleteTitle: 'Aula concluída!',
      AppStrings.academyLearningProgressPill: '+{xp} XP · progresso de aprendizado',
      AppStrings.academyContentLabel: 'CONTEÚDO EDUCATIVO',
      AppStrings.academyExampleLabel: 'EXEMPLO',
      AppStrings.academyLessonOfLabel: 'Aula {n} de {total}',
      AppStrings.mentorInterpretationLabel: 'MENTOR · INTERPRETAÇÃO DE IA',
      AppStrings.academyAllModulesTitle: 'Sua trilha completa',
      AppStrings.academyJourneySubtitle: 'Sua jornada de investimentos',
      AppStrings.academyJourneyExploreTooltip: 'Ver a trilha completa',
      AppStrings.academyJourneyYouAreHere: 'Você está aqui',
      AppStrings.academyJourneyUpNext: 'A seguir',
      AppStrings.academyJourneyContinueLesson: 'Continuar aula',
      AppStrings.academyJourneyStageProgress: '{completed} de {total} aulas',
      AppStrings.academyJourneyStageCompleted: '{completed}/{total} concluídas',
      AppStrings.academyJourneyStageTotalLessons: '{total} aulas',
      AppStrings.academyJourneyStageNotStarted: '{total} aulas · ainda não iniciada',
      AppStrings.academyJourneyModuleProgress: '{completed}/{total} aulas',
      AppStrings.academyJourneyBadgeInProgress: 'em andamento',
      AppStrings.academyJourneyLessonMinutes: '~{minutes} min',
      AppStrings.walletBridgeCtaLabel: 'Ver isso na sua carteira real',
      AppStrings.walletBridgeComingSoon: 'Em breve na Wallet',
      AppStrings.simulatedWalletTitle: 'Carteira Simulada',
      AppStrings.simulatedWalletDisclaimer:
          'Carteira de simulação: você informa os ativos e as datas, e as cotações são reais. Nenhuma ordem é executada e não há conexão com B3, corretora, banco ou exchange. Não é recomendação financeira — resultados simulados não garantem resultados reais.',
      AppStrings.simulatedWalletNoPositions:
          'Você ainda não tem posições simuladas. Que tal registrar sua primeira operação?',
      AppStrings.simulatedWalletResetAction: 'Reiniciar simulação',
      AppStrings.simulatedWalletResetConfirmTitle: 'Reiniciar simulação?',
      AppStrings.simulatedWalletResetConfirmMessage:
          'Isso apaga todas as posições e operações simuladas. Essa ação não pode ser desfeita.',
      AppStrings.simulatedWalletResetConfirmAction: 'Reiniciar',
      AppStrings.simulatedWalletResetSuccess: 'Simulação reiniciada',
      AppStrings.simulatedOrderScreenTitle: 'Nova operação simulada',
      AppStrings.simulatedOrderSearchHint: 'Buscar ativo (ex: PETR4)',
      AppStrings.simulatedOrderBuyLabel: 'Comprar',
      AppStrings.simulatedOrderSellLabel: 'Vender',
      AppStrings.simulatedOrderQuantityLabel: 'Quantidade',
      AppStrings.simulatedOrderReferencePriceLabel: 'Preço de referência (simulado)',
      AppStrings.simulatedOrderConfirmAction: 'Confirmar operação simulada',
      AppStrings.simulatedOrderSuccessMessage: 'Operação simulada registrada',
      AppStrings.simulatedOrderSelectAssetFirst: 'Busque e selecione um ativo primeiro',
      AppStrings.simulatedOrderDateLabel: 'Data da operação',
      AppStrings.simulatedOrderDateToday: 'Hoje',
      AppStrings.simulatedOrderHistoricalPriceLabel: 'Preço de fechamento em',
      AppStrings.simulatedOrderNoHistoricalQuote: 'Sem cotação disponível para esta data',
      AppStrings.simulatedWalletAllocationTitle: 'Alocação simulada',
      AppStrings.simulatedWalletTotalPatrimonyLabel: 'Patrimônio total simulado',
      AppStrings.simulatedWalletResultLabel: 'Resultado',
      AppStrings.simulatedWalletReturnLabel: 'Retorno sobre o investido',
      AppStrings.simulatedWalletPriceUnavailable: 'Preço indisponível',
      AppStrings.simulatedWalletHeaderSubtitle: 'Pratique investir, sem dinheiro de verdade',
      AppStrings.simulatedWalletAddAssetLabel: 'Adicionar',
      AppStrings.simulatedWalletMyAssetsLabel: 'MEUS ATIVOS SIMULADOS',
      AppStrings.simulatedWalletAllocationEmpty: 'Sem dados suficientes para calcular sua alocação.',
      AppStrings.simulatedWalletAllocationCenterLabel: 'TOTAL',
      AppStrings.simulatedWalletWealthBarsTitle: 'Evolução do patrimônio simulado',
      AppStrings.simulatedWalletWealthBarsRangeChip: '12 meses',
      AppStrings.simulatedWalletWealthBarsLegendInvested: 'Valor aplicado',
      AppStrings.simulatedWalletWealthBarsLegendGain: 'Ganho de capital',
      AppStrings.simulatedWalletWealthBarsLegendShortfall: 'Abaixo do aplicado',
      AppStrings.simulatedWalletWealthBarsEmpty: 'Ainda não há histórico suficiente para montar esse gráfico.',
      AppStrings.simulatedWalletSelectTypeError: 'Escolha o tipo do ativo',
      AppStrings.simulatedWalletTypeMismatchWarning: 'Esse ticker parece ser {detected}, não {selected}.',
      AppStrings.simulatedWalletEmptyStateTitle: 'Monte sua carteira simulada',
      AppStrings.simulatedWalletEmptyStateBody:
          'Adicione seu primeiro ativo e a data em que o compraria para acompanhar quanto você ganharia ou perderia de verdade.',
      AppStrings.simulatedWalletEmptyStateCta: 'Adicionar primeiro ativo',
      AppStrings.holdingQuoteUnavailable: 'sem cotação',
      AppStrings.holdingNotQuoted: 'não cotado',
      AppStrings.homeKnowledgeMapLabel: 'SUA TRILHA',
      AppStrings.homeViewFullAcademyCta: 'Ver todas as escolas',
      AppStrings.homeGreetingWithName: 'Bem-vindo de volta, {name}',
      AppStrings.homeStreakDaysLabel: '{days} dias',
      AppStrings.homeContinueGoalSubtitle: 'Baseado no seu objetivo: {goal}',
      AppStrings.homeMentorReasonContinue: 'Baseado na sua última aula concluída.',
      AppStrings.homeMentorReasonReview: 'Baseado em conceitos pendentes de revisão.',
      AppStrings.homeMentorReasonReturn: 'Baseado no tempo desde sua última visita.',
      AppStrings.homeMentorSourcesLabel: 'Fontes consultadas (RAG)',
      AppStrings.homeMentorSourceContinue1: 'Sua última aula concluída',
      AppStrings.homeMentorSourceContinue2: 'Seu progresso na trilha atual',
      AppStrings.homeMentorSourceContinue3: 'Guia interno de sequenciamento de conteúdo',
      AppStrings.homeMentorSourceReview1: 'Aulas com desempenho baixo no quiz',
      AppStrings.homeMentorSourceReview2: 'Seu histórico de revisões',
      AppStrings.homeMentorSourceReview3: 'Guia interno de repetição espaçada',
      AppStrings.homeMentorSourceReturn1: 'Tempo desde sua última visita',
      AppStrings.homeMentorSourceReturn2: 'Sua trilha em andamento',
      AppStrings.homeMentorSourceReturn3: 'Guia interno de retomada após pausa',
      AppStrings.mentorHeaderTitle: 'Seu Mentor',
      AppStrings.mentorHeaderSubtitle: 'Tira dúvidas e explica conceitos — não é conselho financeiro',
      AppStrings.mentorStageGreeting: 'Oi, {name} 👋',
      AppStrings.mentorStageGreetingNoName: 'Oi 👋',
      AppStrings.mentorStageGreetingPrompt: 'O que vamos aprender hoje?',
      AppStrings.mentorStageThinkingTitle: 'Deixa eu pensar nisso...',
      AppStrings.mentorStageThinkingSubtitle: 'Só um segundo.',
      AppStrings.mentorStageAskSomethingElse: 'Perguntar outra coisa',
      AppStrings.mentorStageInputHint: 'Pergunte algo ao seu mentor...',
      AppStrings.labSimulatedDataBadge: 'Simulação — dados fictícios, não é sua carteira real',
      AppStrings.portfolioMilestoneUnlocked: 'Novo marco: {title}',
    },
    // Português europeu. Deliberadamente esparso: só as entradas que diferem
    // do pt-BR. Todo o resto resolve pelo fallback de [translate] para o bloco
    // 'pt', que aqui é o comportamento certo — as duas variantes partilham a
    // maior parte da língua, e uma chave em falta não é um buraco de tradução.
    // O teste 'pt_PT só define chaves que pt também define' impede órfãs.
    'pt_PT': {
      AppStrings.brandTagline: 'Aprenda a investir a jogar',
      AppStrings.gamificationIntroCompareRuleBody:
          'O seu progresso é só seu. Não existe ranking de património ou retorno aqui.',
    },
    'en': {
      AppStrings.brandTitle: 'Petrimonium',
      AppStrings.brandTagline: 'Learn investing by playing',
      AppStrings.logoutConfirmTitle: 'Leave Petrimonium Academy?',
      AppStrings.createAccount: 'Create Account',
      AppStrings.fillDetails: 'Fill in your details',
      AppStrings.alreadyHaveAccount: 'Already have an account? Login',
      AppStrings.meetPetTitle: 'Choose your journey partner',
      AppStrings.meetPetIntro: 'It grows with what you learn — never with how much you have.',
      AppStrings.financialGoalTitle: "What's your goal right now?",
      AppStrings.financialGoalSubtitle: 'This shapes your path. You can change it later.',
      AppStrings.welcomeHeadline: 'Learn finance by practicing, safely.',
      AppStrings.welcomeSubheadline: 'PETRIMONIUM ACADEMY',
      AppStrings.shareProgressCta: 'Download Petrimonium Academy and start your journey',
      AppStrings.inAppBrandName: 'Petrimonium Academy',
      AppStrings.academyIntroTitle: 'Your track starts here',
      AppStrings.academyIntroSubtitle: 'The rest unlocks as you go — no skipping steps.',
      AppStrings.academyIntroStartsNow: 'starts now',
      AppStrings.academyIntroMentorIntro: "Let's start with {module}. {count} — you can do it now.",
      AppStrings.academyIntroLessonSingular: 'lesson',
      AppStrings.academyIntroLessonPlural: 'lessons',
      AppStrings.gamificationIntroTitle: 'How you progress here',
      AppStrings.gamificationIntroXpRuleTitle: 'XP for learning',
      AppStrings.gamificationIntroXpRuleBody:
          'You earn XP by completing lessons and practice — never for returns, deposits, or trades.',
      AppStrings.gamificationIntroStreakRuleTitle: 'No-punishment streak',
      AppStrings.gamificationIntroStreakRuleBody:
          "Missing a day doesn't reset your progress or penalize you — your pet just misses you.",
      AppStrings.gamificationIntroCompareRuleTitle: 'No comparing with others',
      AppStrings.gamificationIntroCompareRuleBody:
          "Your progress is yours alone. There's no net worth or returns leaderboard here.",
      AppStrings.timeHorizonTitle: 'When is this goal for?',
      AppStrings.timeHorizonSubtitle: "Not sure? That's fine, it's just a starting point.",
      AppStrings.experienceLevelTitle: "How's your experience today?",
      AppStrings.experienceLevelSubtitle: "This way the Academy won't teach you what you already know.",
      AppStrings.academyLessonCompleteTitle: 'Lesson complete!',
      AppStrings.academyLearningProgressPill: '+{xp} XP · learning progress',
      AppStrings.academyContentLabel: 'EDUCATIONAL CONTENT',
      AppStrings.academyExampleLabel: 'EXAMPLE',
      AppStrings.academyLessonOfLabel: 'Lesson {n} of {total}',
      AppStrings.mentorInterpretationLabel: 'MENTOR · AI INTERPRETATION',
      AppStrings.academyAllModulesTitle: 'Your full track',
      AppStrings.academyJourneySubtitle: 'Your investing journey',
      AppStrings.academyJourneyExploreTooltip: 'See the full track',
      AppStrings.academyJourneyYouAreHere: "You're here",
      AppStrings.academyJourneyUpNext: 'Up next',
      AppStrings.academyJourneyContinueLesson: 'Continue lesson',
      AppStrings.academyJourneyStageProgress: '{completed} of {total} lessons',
      AppStrings.academyJourneyStageCompleted: '{completed}/{total} done',
      AppStrings.academyJourneyStageTotalLessons: '{total} lessons',
      AppStrings.academyJourneyStageNotStarted: '{total} lessons · not started yet',
      AppStrings.academyJourneyModuleProgress: '{completed}/{total} lessons',
      AppStrings.academyJourneyBadgeInProgress: 'in progress',
      AppStrings.academyJourneyLessonMinutes: '~{minutes} min',
      AppStrings.walletBridgeCtaLabel: 'See this in your real portfolio',
      AppStrings.walletBridgeComingSoon: 'Coming soon in Wallet',
      AppStrings.simulatedWalletTitle: 'Simulated Wallet',
      AppStrings.simulatedWalletDisclaimer:
          'Simulation wallet: you enter the assets and dates, and quotes are real. No order is executed and there is no connection to any exchange, broker, or bank. Not financial advice — simulated results do not guarantee real results.',
      AppStrings.simulatedWalletNoPositions:
          "You don't have any simulated positions yet. How about placing your first order?",
      AppStrings.simulatedWalletResetAction: 'Reset simulation',
      AppStrings.simulatedWalletResetConfirmTitle: 'Reset simulation?',
      AppStrings.simulatedWalletResetConfirmMessage:
          'This erases every simulated position and order. This cannot be undone.',
      AppStrings.simulatedWalletResetConfirmAction: 'Reset',
      AppStrings.simulatedWalletResetSuccess: 'Simulation reset',
      AppStrings.simulatedOrderScreenTitle: 'New simulated order',
      AppStrings.simulatedOrderSearchHint: 'Search an asset (e.g. PETR4)',
      AppStrings.simulatedOrderBuyLabel: 'Buy',
      AppStrings.simulatedOrderSellLabel: 'Sell',
      AppStrings.simulatedOrderQuantityLabel: 'Quantity',
      AppStrings.simulatedOrderReferencePriceLabel: 'Reference price (simulated)',
      AppStrings.simulatedOrderConfirmAction: 'Confirm simulated order',
      AppStrings.simulatedOrderSuccessMessage: 'Simulated order placed',
      AppStrings.simulatedOrderSelectAssetFirst: 'Search and select an asset first',
      AppStrings.simulatedOrderDateLabel: 'Order date',
      AppStrings.simulatedOrderDateToday: 'Today',
      AppStrings.simulatedOrderHistoricalPriceLabel: 'Closing price on',
      AppStrings.simulatedOrderNoHistoricalQuote: 'No quote available for this date',
      AppStrings.simulatedWalletAllocationTitle: 'Simulated allocation',
      AppStrings.simulatedWalletTotalPatrimonyLabel: 'Total simulated patrimony',
      AppStrings.simulatedWalletResultLabel: 'Result',
      AppStrings.simulatedWalletReturnLabel: 'Return on invested',
      AppStrings.simulatedWalletPriceUnavailable: 'Price unavailable',
      AppStrings.simulatedWalletHeaderSubtitle: 'Practice investing, with no real money',
      AppStrings.simulatedWalletAddAssetLabel: 'Add',
      AppStrings.simulatedWalletMyAssetsLabel: 'MY SIMULATED ASSETS',
      AppStrings.simulatedWalletAllocationEmpty: "There isn't enough data to work out your allocation.",
      AppStrings.simulatedWalletAllocationCenterLabel: 'TOTAL',
      AppStrings.simulatedWalletWealthBarsTitle: 'Simulated wealth evolution',
      AppStrings.simulatedWalletWealthBarsRangeChip: '12 months',
      AppStrings.simulatedWalletWealthBarsLegendInvested: 'Invested capital',
      AppStrings.simulatedWalletWealthBarsLegendGain: 'Capital gain',
      AppStrings.simulatedWalletWealthBarsLegendShortfall: 'Below invested',
      AppStrings.simulatedWalletWealthBarsEmpty: "There isn't enough history yet to draw this chart.",
      AppStrings.simulatedWalletSelectTypeError: 'Pick the asset type',
      AppStrings.simulatedWalletTypeMismatchWarning: 'That ticker looks like {detected}, not {selected}.',
      AppStrings.simulatedWalletEmptyStateTitle: 'Build your simulated portfolio',
      AppStrings.simulatedWalletEmptyStateBody:
          'Add your first asset and the date you would have bought it to track how much you would really gain or lose.',
      AppStrings.simulatedWalletEmptyStateCta: 'Add first asset',
      AppStrings.holdingQuoteUnavailable: 'no quote',
      AppStrings.holdingNotQuoted: 'not quoted',
      AppStrings.homeKnowledgeMapLabel: 'YOUR TRACK',
      AppStrings.homeViewFullAcademyCta: 'See all schools',
      AppStrings.homeGreetingWithName: 'Welcome back, {name}',
      AppStrings.homeStreakDaysLabel: '{days} days',
      AppStrings.homeContinueGoalSubtitle: 'Based on your goal: {goal}',
      AppStrings.homeMentorReasonContinue: 'Based on your last completed lesson.',
      AppStrings.homeMentorReasonReview: 'Based on concepts due for review.',
      AppStrings.homeMentorReasonReturn: "Based on how long it's been since your last visit.",
      AppStrings.homeMentorSourcesLabel: 'Sources consulted (RAG)',
      AppStrings.homeMentorSourceContinue1: 'Your last completed lesson',
      AppStrings.homeMentorSourceContinue2: 'Your progress on the current path',
      AppStrings.homeMentorSourceContinue3: 'Internal content-sequencing guide',
      AppStrings.homeMentorSourceReview1: 'Lessons with low quiz performance',
      AppStrings.homeMentorSourceReview2: 'Your review history',
      AppStrings.homeMentorSourceReview3: 'Internal spaced-repetition guide',
      AppStrings.homeMentorSourceReturn1: 'Time since your last visit',
      AppStrings.homeMentorSourceReturn2: 'Your path in progress',
      AppStrings.homeMentorSourceReturn3: 'Internal return-after-pause guide',
      AppStrings.mentorHeaderTitle: 'Your Mentor',
      AppStrings.mentorHeaderSubtitle: 'Answers questions and explains concepts — not financial advice',
      AppStrings.mentorStageGreeting: 'Hi, {name} 👋',
      AppStrings.mentorStageGreetingNoName: 'Hi 👋',
      AppStrings.mentorStageGreetingPrompt: 'What shall we learn today?',
      AppStrings.mentorStageThinkingTitle: 'Let me think about that...',
      AppStrings.mentorStageThinkingSubtitle: 'Just a second.',
      AppStrings.mentorStageAskSomethingElse: 'Ask something else',
      AppStrings.mentorStageInputHint: 'Ask your mentor something...',
      AppStrings.labSimulatedDataBadge: 'Simulation — fictional data, not your real portfolio',
      AppStrings.portfolioMilestoneUnlocked: 'New milestone: {title}',
    },
    'es': {
      AppStrings.brandTitle: 'Petrimonium',
      AppStrings.brandTagline: 'Aprende a invertir jugando',
      AppStrings.logoutConfirmTitle: '¿Salir de Petrimonium Academy?',
      AppStrings.createAccount: 'Crear Cuenta',
      AppStrings.fillDetails: 'Completa tus datos',
      AppStrings.alreadyHaveAccount: '¿Ya tienes cuenta? Entrar',
      AppStrings.meetPetTitle: 'Elige tu compañero de viaje',
      AppStrings.meetPetIntro: 'Evoluciona con lo que aprendes — nunca con cuánto tienes.',
      AppStrings.financialGoalTitle: '¿Cuál es tu objetivo ahora?',
      AppStrings.financialGoalSubtitle: 'Esto ajusta tu camino. Puedes cambiarlo después.',
      AppStrings.welcomeHeadline: 'Aprende finanzas practicando con seguridad.',
      AppStrings.welcomeSubheadline: 'PETRIMONIUM ACADEMY',
      AppStrings.shareProgressCta: 'Descarga Petrimonium Academy y comienza tu viaje',
      AppStrings.inAppBrandName: 'Petrimonium Academy',
      AppStrings.academyIntroTitle: 'Tu camino comienza aquí',
      AppStrings.academyIntroSubtitle: 'El resto se desbloquea a medida que avanzas — sin saltar pasos.',
      AppStrings.academyIntroStartsNow: 'empieza ahora',
      AppStrings.academyIntroMentorIntro: 'Empecemos por {module}. {count} — puedes hacerlo ahora.',
      AppStrings.academyIntroLessonSingular: 'lección',
      AppStrings.academyIntroLessonPlural: 'lecciones',
      AppStrings.gamificationIntroTitle: 'Cómo progresas aquí',
      AppStrings.gamificationIntroXpRuleTitle: 'XP por aprender',
      AppStrings.gamificationIntroXpRuleBody:
          'Ganas XP completando lecciones y prácticas — nunca por valorización, aportes u operaciones.',
      AppStrings.gamificationIntroStreakRuleTitle: 'Racha sin penalización',
      AppStrings.gamificationIntroStreakRuleBody:
          'Perder un día no reinicia tu progreso ni te penaliza — tu mascota solo te extraña.',
      AppStrings.gamificationIntroCompareRuleTitle: 'Sin comparación entre personas',
      AppStrings.gamificationIntroCompareRuleBody:
          'Tu progreso es solo tuyo. Aquí no existe un ranking de patrimonio ni de rentabilidad.',
      AppStrings.timeHorizonTitle: '¿Para cuándo es ese objetivo?',
      AppStrings.timeHorizonSubtitle: '¿No estás seguro? Está bien, es solo un punto de partida.',
      AppStrings.experienceLevelTitle: '¿Cómo está tu experiencia hoy?',
      AppStrings.experienceLevelSubtitle: 'Así la Academy no te enseña lo que ya sabes.',
      AppStrings.academyLessonCompleteTitle: '¡Lección completada!',
      AppStrings.academyLearningProgressPill: '+{xp} XP · progreso de aprendizaje',
      AppStrings.academyContentLabel: 'CONTENIDO EDUCATIVO',
      AppStrings.academyExampleLabel: 'EJEMPLO',
      AppStrings.academyLessonOfLabel: 'Lección {n} de {total}',
      AppStrings.mentorInterpretationLabel: 'MENTOR · INTERPRETACIÓN DE IA',
      AppStrings.academyAllModulesTitle: 'Tu ruta completa',
      AppStrings.academyJourneySubtitle: 'Tu recorrido de inversiones',
      AppStrings.academyJourneyExploreTooltip: 'Ver la ruta completa',
      AppStrings.academyJourneyYouAreHere: 'Estás aquí',
      AppStrings.academyJourneyUpNext: 'A continuación',
      AppStrings.academyJourneyContinueLesson: 'Continuar lección',
      AppStrings.academyJourneyStageProgress: '{completed} de {total} lecciones',
      AppStrings.academyJourneyStageCompleted: '{completed}/{total} completadas',
      AppStrings.academyJourneyStageTotalLessons: '{total} lecciones',
      AppStrings.academyJourneyStageNotStarted: '{total} lecciones · aún sin empezar',
      AppStrings.academyJourneyModuleProgress: '{completed}/{total} lecciones',
      AppStrings.academyJourneyBadgeInProgress: 'en curso',
      AppStrings.academyJourneyLessonMinutes: '~{minutes} min',
      AppStrings.walletBridgeCtaLabel: 'Ver esto en tu cartera real',
      AppStrings.walletBridgeComingSoon: 'Próximamente en Wallet',
      AppStrings.simulatedWalletTitle: 'Cartera Simulada',
      AppStrings.simulatedWalletDisclaimer:
          'Cartera de simulación: tú indicas los activos y las fechas, y las cotizaciones son reales. No se ejecuta ninguna orden y no hay conexión con ninguna bolsa, corredora o banco. No es una recomendación financiera — los resultados simulados no garantizan resultados reales.',
      AppStrings.simulatedWalletNoPositions:
          'Aún no tienes posiciones simuladas. ¿Qué tal registrar tu primera operación?',
      AppStrings.simulatedWalletResetAction: 'Reiniciar simulación',
      AppStrings.simulatedWalletResetConfirmTitle: '¿Reiniciar simulación?',
      AppStrings.simulatedWalletResetConfirmMessage:
          'Esto borra todas las posiciones y operaciones simuladas. Esta acción no se puede deshacer.',
      AppStrings.simulatedWalletResetConfirmAction: 'Reiniciar',
      AppStrings.simulatedWalletResetSuccess: 'Simulación reiniciada',
      AppStrings.simulatedOrderScreenTitle: 'Nueva operación simulada',
      AppStrings.simulatedOrderSearchHint: 'Buscar activo (ej: PETR4)',
      AppStrings.simulatedOrderBuyLabel: 'Comprar',
      AppStrings.simulatedOrderSellLabel: 'Vender',
      AppStrings.simulatedOrderQuantityLabel: 'Cantidad',
      AppStrings.simulatedOrderReferencePriceLabel: 'Precio de referencia (simulado)',
      AppStrings.simulatedOrderConfirmAction: 'Confirmar operación simulada',
      AppStrings.simulatedOrderSuccessMessage: 'Operación simulada registrada',
      AppStrings.simulatedOrderSelectAssetFirst: 'Busca y selecciona un activo primero',
      AppStrings.simulatedOrderDateLabel: 'Fecha de la operación',
      AppStrings.simulatedOrderDateToday: 'Hoy',
      AppStrings.simulatedOrderHistoricalPriceLabel: 'Precio de cierre del',
      AppStrings.simulatedOrderNoHistoricalQuote: 'Sin cotización disponible para esta fecha',
      AppStrings.simulatedWalletAllocationTitle: 'Asignación simulada',
      AppStrings.simulatedWalletTotalPatrimonyLabel: 'Patrimonio total simulado',
      AppStrings.simulatedWalletResultLabel: 'Resultado',
      AppStrings.simulatedWalletReturnLabel: 'Retorno sobre lo invertido',
      AppStrings.simulatedWalletPriceUnavailable: 'Precio no disponible',
      AppStrings.simulatedWalletHeaderSubtitle: 'Practica invertir, sin dinero real',
      AppStrings.simulatedWalletAddAssetLabel: 'Agregar',
      AppStrings.simulatedWalletMyAssetsLabel: 'MIS ACTIVOS SIMULADOS',
      AppStrings.simulatedWalletAllocationEmpty: 'No hay suficientes datos para calcular tu asignación.',
      AppStrings.simulatedWalletAllocationCenterLabel: 'TOTAL',
      AppStrings.simulatedWalletWealthBarsTitle: 'Evolución del patrimonio simulado',
      AppStrings.simulatedWalletWealthBarsRangeChip: '12 meses',
      AppStrings.simulatedWalletWealthBarsLegendInvested: 'Valor aplicado',
      AppStrings.simulatedWalletWealthBarsLegendGain: 'Ganancia de capital',
      AppStrings.simulatedWalletWealthBarsLegendShortfall: 'Por debajo de lo aplicado',
      AppStrings.simulatedWalletWealthBarsEmpty: 'Todavía no hay suficiente historial para armar este gráfico.',
      AppStrings.simulatedWalletSelectTypeError: 'Elige el tipo de activo',
      AppStrings.simulatedWalletTypeMismatchWarning: 'Ese ticker parece ser {detected}, no {selected}.',
      AppStrings.simulatedWalletEmptyStateTitle: 'Arma tu cartera simulada',
      AppStrings.simulatedWalletEmptyStateBody:
          'Agrega tu primer activo y la fecha en que lo comprarías para ver cuánto ganarías o perderías de verdad.',
      AppStrings.simulatedWalletEmptyStateCta: 'Agregar primer activo',
      AppStrings.holdingQuoteUnavailable: 'sin cotización',
      AppStrings.holdingNotQuoted: 'no cotizado',
      AppStrings.homeKnowledgeMapLabel: 'TU RUTA',
      AppStrings.homeViewFullAcademyCta: 'Ver todas las escuelas',
      AppStrings.homeGreetingWithName: 'Bienvenido de nuevo, {name}',
      AppStrings.homeStreakDaysLabel: '{days} días',
      AppStrings.homeContinueGoalSubtitle: 'Basado en tu objetivo: {goal}',
      AppStrings.homeMentorWhySeeing: '¿Por qué estoy viendo esto?',
      AppStrings.homeMentorReasonContinue: 'Basado en tu última lección completada.',
      AppStrings.homeMentorReasonReview: 'Basado en conceptos pendientes de repaso.',
      AppStrings.homeMentorReasonReturn: 'Basado en el tiempo desde tu última visita.',
      AppStrings.homeMentorSourcesLabel: 'Fuentes consultadas (RAG)',
      AppStrings.homeMentorSourceContinue1: 'Tu última lección completada',
      AppStrings.homeMentorSourceContinue2: 'Tu progreso en la ruta actual',
      AppStrings.homeMentorSourceContinue3: 'Guía interna de secuenciación de contenido',
      AppStrings.homeMentorSourceReview1: 'Lecciones con bajo desempeño en el quiz',
      AppStrings.homeMentorSourceReview2: 'Tu historial de repasos',
      AppStrings.homeMentorSourceReview3: 'Guía interna de repetición espaciada',
      AppStrings.homeMentorSourceReturn1: 'Tiempo desde tu última visita',
      AppStrings.homeMentorSourceReturn2: 'Tu ruta en curso',
      AppStrings.homeMentorSourceReturn3: 'Guía interna de retorno tras una pausa',
      AppStrings.mentorHeaderTitle: 'Tu Mentor',
      AppStrings.mentorHeaderSubtitle: 'Responde dudas y explica conceptos — no es asesoría financiera',
      AppStrings.mentorStageGreeting: 'Hola, {name} 👋',
      AppStrings.mentorStageGreetingNoName: 'Hola 👋',
      AppStrings.mentorStageGreetingPrompt: '¿Qué vamos a aprender hoy?',
      AppStrings.mentorStageThinkingTitle: 'Déjame pensar en eso...',
      AppStrings.mentorStageThinkingSubtitle: 'Solo un segundo.',
      AppStrings.mentorStageAskSomethingElse: 'Preguntar otra cosa',
      AppStrings.mentorStageInputHint: 'Pregúntale algo a tu mentor...',
      AppStrings.labSimulatedDataBadge: 'Simulación — datos ficticios, no es tu cartera real',
      AppStrings.portfolioMilestoneUnlocked: 'Nuevo hito: {title}',
    },
  };
}
